## Sentiment Analysis (Reddit)

In [4]:
import pandas as pd
df = pd.read_csv(r"C:\Users\prath\Downloads\Practicals\Datasets\reddit_wsb.csv")

In [5]:
df

,title,score,id,url,comms_num,created,body,timestamp
0,"It's not about the money, it's about sending a...",55,l6ulcx,https://v.redd.it/6j75regs72e61,6,1.611863e+09,NaN,2021-01-28 21:37:41
1,Math Professor Scott Steiner says the numbers ...,110,l6uibd,https://v.redd.it/ah50lyny62e61,23,1.611862e+09,NaN,2021-01-28 21:32:10
2,Exit the system,0,l6uhhn,https://www.reddit.com/r/wallstreetbets/commen...,47,1.611862e+09,The CEO of NASDAQ pushed to halt trading “to g...,2021-01-28 21:30:35
3,NEW SEC FILING FOR GME! CAN SOMEONE LESS RETAR...,29,l6ugk6,https://sec.report/Document/0001193125-21-019848/,74,1.611862e+09,NaN,2021-01-28 21:28:57
4,"Not to distract from GME, just thought our AMC...",71,l6ufgy,https://i.redd.it/4h2sukb662e61.jpg,156,1.611862e+09,NaN,2021-01-28 21:26:56
...,...,...,...,...,...,...,...,...
53182,What I Learned Investigating SAVA FUD Spreaders,238,owd2pn,https://www.reddit.com/r/wallstreetbets/commen...,87,1.627906e+09,***TLDR: Three bitter scientists partnered up ...,2021-08-02 15:03:27
53183,"Daily Popular Tickers Thread for August 02, 20...",228,owd1a5,https://www.reddit.com/r/wallstreetbets/commen...,1070,1.627906e+09,\nYour daily hype thread. Please keep the shit...,2021-08-02 15:01:03
53184,Hitler reacts to the market being irrational,7398,owc5dr,https://v.redd.it/46jxu074exe71,372,1.627902e+09,NaN,2021-08-02 13:59:35
53185,"Daily Discussion Thread for August 02, 2021",338,owbfjf,https://www.reddit.com/r/wallstreetbets/commen...,11688,1.627898e+09,Your daily trading discussion thread. Please k...,2021-08-02 13:00:16
53186,Fraternal Association of Gambling Gentlemen an...,40,owaqd6,https://www.reddit.com/r/wallstreetbets/commen...,810,1.627895e+09,This is an old Yacht Club thread. Click /u/Vis...,2021-08-02 12:00:14

In [6]:
df["text"] = df["title"].fillna('') + " " + df["body"].fillna('')

In [7]:
from textblob import TextBlob

def get_sentiment(text):
    polarity = TextBlob(text).sentiment.polarity
    
    if polarity > 0:
        return "Positive"
    elif polarity < 0:
        return "Negative"
    else:
        return "Neutral"

df["sentiment"] = df["text"].apply(get_sentiment)

In [8]:
print(df[["text", "sentiment"]].head())

                                                text sentiment
0  It's not about the money, it's about sending a...   Neutral
1  Math Professor Scott Steiner says the numbers ...   Neutral
2  Exit the system The CEO of NASDAQ pushed to ha...  Positive
3  NEW SEC FILING FOR GME! CAN SOMEONE LESS RETAR...  Negative
4  Not to distract from GME, just thought our AMC...  Positive

In [9]:
print(df["sentiment"].value_counts())

sentiment
Positive    22981
Neutral     18171
Negative    12035
Name: count, dtype: int64

Positive → hype / bullish posts 🚀  
Negative → fear / panic 😨  
Neutral → normal discussion

## 🔷 2. FINANCIAL NEWS + SENTIMENT

In [11]:
import pandas as pd
df = pd.read_csv(r"C:\Users\prath\Downloads\Practicals\Datasets\finacial_news.csv")

In [12]:
df

                                               Sentence Sentiment
0     The GeoSolutions technology will leverage Bene...  positive
1     $ESI on lows, down $1.50 to $2.50 BK a real po...  negative
2     For the last quarter of 2010 , Componenta 's n...  positive
3     According to the Finnish-Russian Chamber of Co...   neutral
4     The Swedish buyout firm has sold its remaining...   neutral
...                                                 ...       ...
5837  RISING costs have forced packaging producer Hu...  negative
5838  Nordic Walking was first used as a summer trai...   neutral
5839  According shipping company Viking Line , the E...   neutral
5840  In the building and home improvement trade , s...   neutral
5841  HELSINKI AFX - KCI Konecranes said it has won ...  positive

[5842 rows x 2 columns]

In [13]:
df.columns = ["text", "sentiment"]   # if needed

In [14]:
df["sentiment"] = df["sentiment"].map({
    "negative": 0,
    "neutral": 1,
    "positive": 2
})

In [15]:
from sklearn.model_selection import train_test_split

X = df["text"]
y = df["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [17]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [18]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.6663815226689478
              precision    recall  f1-score   support

           0       0.85      0.06      0.12       175
           1       0.65      0.97      0.78       622
           2       0.72      0.44      0.54       372

    accuracy                           0.67      1169
   macro avg       0.74      0.49      0.48      1169
weighted avg       0.70      0.67      0.61      1169