### Part  1: AI PRODUCT (Amazon review)

In [7]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [10]:
df = pd.read_csv(r"C:\Users\prath\Downloads\Practicals\Datasets\amazon_review.csv")

In [11]:
df

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,3.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,This is not the same remote that I got for my ...,I would be disappointed with myself if i produ...,NaN,NaN,GregAmandawith4,NaN,NaN,4 ounces
1593,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,1.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,I have had to change the batteries in this rem...,Battery draining remote!!!!,NaN,NaN,Amazon Customer,NaN,NaN,4 ounces
1594,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,1.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,"Remote did not activate, nor did it connect to...",replacing an even worse remote. Waste of time,NaN,NaN,Amazon Customer,NaN,NaN,4 ounces
1595,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,3.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,It does the job but is super over priced. I fe...,Overpriced,NaN,NaN,Meg Ashley,NaN,NaN,4 ounces
1596,AVpfo9ukilAPnD_xfhuj,B00NO8JJZW,Amazon,"Amazon Devices & Accessories,Amazon Device Acc...",NaN,2016-04-02T14:40:43Z,2017-08-13T08:28:46Z,NaN,NaN,alexavoiceremoteforamazonfiretvfiretvstick/b00...,...,1.0,https://www.amazon.com/Alexa-Voice-Remote-Amaz...,I ordered this item to replace the one that no...,I am sending all of this crap back to amazon a...,NaN,NaN,DIANE K,NaN,NaN,4 ounces

In [12]:
df = df[["reviews.text", "reviews.rating"]]
df = df.dropna()

In [13]:
df

                                           reviews.text  reviews.rating
0     I initially had trouble deciding between the p...             5.0
1     Allow me to preface this with a little history...             5.0
2     I am enjoying it so far. Great for reading. Ha...             4.0
3     I bought one of the first Paperwhites and have...             5.0
4     I have to say upfront - I don't like coroporat...             5.0
...                                                 ...             ...
1592  This is not the same remote that I got for my ...             3.0
1593  I have had to change the batteries in this rem...             1.0
1594  Remote did not activate, nor did it connect to...             1.0
1595  It does the job but is super over priced. I fe...             3.0
1596  I ordered this item to replace the one that no...             1.0

[1177 rows x 2 columns]

In [14]:
def get_sentiment(rating):
    if rating >= 4:
        return "Positive"
    else:
        return "Negative"

df["sentiment"] = df["reviews.rating"].apply(get_sentiment)

In [16]:
X = df["reviews.text"]
y = df["sentiment"]

In [17]:
vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')

X = vectorizer.fit_transform(X)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [19]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [20]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8813559322033898

## Part 2 :AI Bias in Hiring Systems

In [21]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [22]:
df = pd.read_csv("./Datasets/hiring.csv")
print(df.head())

   gender  age education_level  experience_years  screening_score  shortlisted
0    Male   35         Masters                 1        72.473130            0
1  Female   32       Bachelors                15        55.004084            0
2    Male   36         Masters                19        60.156004            0
3    Male   44       Bachelors                 6        75.846397            0
4    Male   39     High School                 1        43.297540            1

In [23]:
df

,gender,age,education_level,experience_years,screening_score,shortlisted
0,Male,35,Masters,1,72.473130,0
1,Female,32,Bachelors,15,55.004084,0
2,Male,36,Masters,19,60.156004,0
3,Male,44,Bachelors,6,75.846397,0
4,Male,39,High School,1,43.297540,1
...,...,...,...,...,...,...
1995,Male,29,Masters,15,67.250957,0
1996,Female,24,Bachelors,14,73.093133,1
1997,Male,25,Bachelors,1,71.634872,0
1998,Male,41,High School,8,65.387954,0
1999,Male,28,High School,6,74.166009,0

In [24]:
le_gender = LabelEncoder()
le_edu = LabelEncoder()

df["gender"] = le_gender.fit_transform(df["gender"])
df["education_level"] = le_edu.fit_transform(df["education_level"])

In [25]:
X = df.drop("shortlisted", axis=1)
y = df["shortlisted"]

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [27]:
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [28]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.53

In [29]:
print(df.groupby("gender")["shortlisted"].mean())

gender
0    0.420732
1    0.384843
Name: shortlisted, dtype: float64

🧠 Interpretation
If values are very different → ❌ Bias present
If similar → ✅ Fair model

How to Reduce Bias (Write in Report)
Remove sensitive features (gender)
X = df.drop(["shortlisted", "gender"], axis=1)

### Ethical (Fake News)

In [48]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [49]:
df = pd.read_csv("./Datasets/fake_news_dataset.csv")

# combine title + text (best practice)
df["content"] = df["title"] + " " + df["text"]

df = df.dropna()

In [50]:
df

,title,text,date,source,author,category,label,content
0,Foreign Democrat final.,more tax development both store agreement lawy...,2023-03-10,NY Times,Paula George,Politics,real,Foreign Democrat final. more tax development b...
1,To offer down resource great point.,probably guess western behind likely next inve...,2022-05-25,Fox News,Joseph Hill,Politics,fake,To offer down resource great point. probably g...
2,Himself church myself carry.,them identify forward present success risk sev...,2022-09-01,CNN,Julia Robinson,Business,fake,Himself church myself carry. them identify for...
3,You unit its should.,phone which item yard Republican safe where po...,2023-02-07,Reuters,Mr. David Foster DDS,Science,fake,You unit its should. phone which item yard Rep...
4,Billion believe employee summer how.,wonder myself fact difficult course forget exa...,2023-04-03,CNN,Austin Walker,Technology,fake,Billion believe employee summer how. wonder my...
...,...,...,...,...,...,...,...,...
19995,House party born.,hit and television I change very our happy doo...,2024-12-04,BBC,Gary Miles,Entertainment,fake,House party born. hit and television I change ...
19996,Though nation people maybe price box.,fear most meet rock even sea value design stan...,2024-05-26,Daily News,Maria Mcbride,Entertainment,real,Though nation people maybe price box. fear mos...
19997,Yet exist with experience unit.,activity loss very provide eye west create wha...,2023-04-17,BBC,Kristen Franklin,Entertainment,real,Yet exist with experience unit. activity loss ...
19998,School wide itself item.,term point general common training watch respo...,2024-06-30,Reuters,David Wise,Health,fake,School wide itself item. term point general co...
19999,Offer chair cover senior born.,remain pressure glass me six senior though nor...,2024-01-24,Daily News,James Peterson,Health,fake,Offer chair cover senior born. remain pressure...

In [51]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)  # remove symbols
    text = re.sub(r'\s+', ' ', text)        # remove extra spaces
    return text

df["content"] = df["content"].apply(clean_text)

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=10000,          # increase features
    ngram_range=(1,2),           # bigrams
    stop_words='english',
    min_df=5                     # remove rare words
)

X = vectorizer.fit_transform(df["content"])

In [56]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [57]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [58]:
from sklearn.metrics import accuracy_score, classification_report
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.49875311720698257
              precision    recall  f1-score   support

        fake       0.51      0.59      0.55      1846
        real       0.48      0.40      0.44      1763

    accuracy                           0.50      3609
   macro avg       0.50      0.50      0.49      3609
weighted avg       0.50      0.50      0.49      3609

In [47]:
print(df["label"].value_counts())

label
fake    9095
real    8950
Name: count, dtype: int64

WHAT TO SAY IN VIVA (VERY IMPORTANT)

If asked:
👉 “Why accuracy was low?”

Say:

“Initial model underperformed due to noisy text and limited feature extraction. We improved performance by applying text preprocessing, increasing TF-IDF features, and using a Naive Bayes model optimized for text classification.”


🛡️ ETHICAL ADD-ON (EXTRA MARKS)

Say:

“Incorrect classification of real news as fake can lead to misinformation suppression, so improving accuracy is critical for ethical AI usage.”